version: '2'

services:
  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - docker_elk
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./security/searchguard-config:/usr/share/elasticsearch/plugins/search-guard-5/sgconfig
      - ./security/certs/:/usr/share/elasticsearch/config/certs/
 
  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/conf/ --config.reload.automatic
    ports:
      - "5000:5000"
      - "5043:5043"
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
      - ./security/certs/truststore.jks:/etc/logstash/certs/truststore.jks
    networks:
      - docker_elk
  
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/kibana.yml:/etc/kibana/kibana.yml
      - ./kibana/config/bundles/images/Vector-based_example.svg:/usr/share/kibana/optimize/bundles/src/ui/public/images/kibana.svg
      - ./security/certs/ca/root-ca.pem:/etc/kibana/certs/root-ca.pem
      - ./security/certs/kibana:/etc/kibana/certs/kibana
    ports:
      - "5601:5601"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch

  filebeat:
    build: filebeat/
    volumes:
      - ./filebeat/config/:/etc/filebeat/
      - ../input/:/var/log/filebeat/
    depends_on:
      - logstash
    networks:
      - docker_elk


networks:
  docker_elk:
    driver: bridge
