version: '2'

services:
  elasticsearch:
    build: elasticsearch/
    #image: elasticsearch:5.1.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - docker_elk
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/config/searchguard-config:/usr/share/elasticsearch/plugins/search-guard-5/sgconfig
      - ../search-guard-ssl/example-pki-scripts/kirk-keystore.jks:/usr/share/elasticsearch/config/kirk-keystore.jks
      - ../search-guard-ssl/example-pki-scripts/node-0-keystore.jks:/usr/share/elasticsearch/config/node-0-keystore.jks
      - ../search-guard-ssl/example-pki-scripts/truststore.jks:/usr/share/elasticsearch/config/truststore.jks
      
  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/conf/ --config.reload.automatic
    ports:
      - "5000:5000"
      - "5043:5043"
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    networks:
      - docker_elk
  
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
      - ./kibana/config/bundles/images/Vector-based_example.svg:/usr/share/kibana/optimize/bundles/src/ui/public/images/kibana.svg
    ports:
      - "5601:5601"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch

  filebeat:
    build: filebeat/
    volumes:
      - ./filebeat/config/:/etc/filebeat/
      - ../input/:/var/log/filebeat/
    depends_on:
      - logstash
    networks:
      - docker_elk


networks:
  docker_elk:
    driver: bridge
